In [47]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt

In [11]:
image=cv.imread('myimage.jpg')
img = cv.resize(image, (300, 200))
img=cv.cvtColor(image, cv.COLOR_RGB2GRAY)

In [21]:
img

array([[232, 236, 236, ..., 222, 223, 223],
       [232, 233, 234, ..., 223, 224, 224],
       [230, 231, 230, ..., 224, 224, 224],
       ...,
       [ 88,  90,  51, ...,   3,   1,   1],
       [ 73,  75,  85, ...,   3,   1,   1],
       [ 90,  74,  52, ...,   2,   1,   3]],
      shape=(847, 1280), dtype=uint8)

In [24]:
img[[1,2]]

array([[232, 233, 234, ..., 223, 224, 224],
       [230, 231, 230, ..., 224, 224, 224]], shape=(2, 1280), dtype=uint8)

In [31]:
img

array([[232, 236, 236, ..., 222, 223, 223],
       [232, 233, 234, ..., 223, 224, 224],
       [230, 231, 230, ..., 224, 224, 224],
       ...,
       [ 88,  90,  51, ...,   3,   1,   1],
       [ 73,  75,  85, ...,   3,   1,   1],
       [ 90,  74,  52, ...,   2,   1,   3]],
      shape=(847, 1280), dtype=uint8)

In [64]:
def voisinage_3(image,p):
    lign=range(p[0]-1,p[0]+2)
    col=range(p[1]-1,p[1]+2)
    return [(lign[k],col[k]) for k in range(len(lign))]

In [65]:
voisinage_3(1,(1,1))

[(0, 0), (1, 1), (2, 2)]

In [55]:
voisinage_3(img,(1,1))

array([232, 236, 236, 232, 233, 234, 230, 231, 230], dtype=uint8)

In [51]:
def norme(p,q):
   return  np.sqrt((p[0]-q[0])**2 +(p[1]-q[1])**2)

In [60]:
def G_fonction(x,sigma):
    return  (1/(np.sqrt(2*np.pi))*sigma)*np.exp(-x**2/(2*(sigma**2)))

In [61]:
G_fonction(2,0.7)

np.float64(0.004713869632661166)

In [ ]:
def bilateral_filter(image,s,sigma):
     for i in range(img.shape[0]):
         for j in range(img.shape[0]):
            voisin=voisinage_3(image,(i,j))
            image[i,j]=np.sum([G_fonction(norme((i,j)))])

