In [2]:
from Tp2 import *
from forTp2 import Grid_Solv

In [5]:
grid_eval= Grid_Solv(4)
s=policy_evaluation(grid_eval)
s

array([  0.        , -13.8687341 , -19.8112877 , -21.79228713,
       -13.8687341 , -17.83891951, -19.82510361, -19.82710344,
       -19.8112877 , -19.82510361, -17.85241947, -13.88981456,
       -21.79228713, -19.82710344, -13.88981456,   0.        ])

# The value fonction avec le random policy . Meme resultats que celui sur le slide du cours. Les cases qui sont proches de notre gaol ont des valeur plus grandes ce qui est logique

In [6]:
s=policy_improvement(grid_eval)
s

{np.int64(0): {'UP': 1, 'RIGHT': 0, 'DOWN': 0, 'LEFT': 0},
 np.int64(1): {'UP': 0, 'RIGHT': 0, 'DOWN': 0, 'LEFT': 1},
 np.int64(2): {'UP': 0, 'RIGHT': 0, 'DOWN': 0, 'LEFT': 1},
 np.int64(3): {'UP': 0, 'RIGHT': 0, 'DOWN': 0, 'LEFT': 1},
 np.int64(4): {'UP': 1, 'RIGHT': 0, 'DOWN': 0, 'LEFT': 0},
 np.int64(5): {'UP': 0, 'RIGHT': 0, 'DOWN': 0, 'LEFT': 1},
 np.int64(6): {'UP': 0, 'RIGHT': 0, 'DOWN': 0, 'LEFT': 1},
 np.int64(7): {'UP': 0, 'RIGHT': 0, 'DOWN': 1, 'LEFT': 0},
 np.int64(8): {'UP': 1, 'RIGHT': 0, 'DOWN': 0, 'LEFT': 0},
 np.int64(9): {'UP': 1, 'RIGHT': 0, 'DOWN': 0, 'LEFT': 0},
 np.int64(10): {'UP': 0, 'RIGHT': 1, 'DOWN': 0, 'LEFT': 0},
 np.int64(11): {'UP': 0, 'RIGHT': 0, 'DOWN': 1, 'LEFT': 0},
 np.int64(12): {'UP': 1, 'RIGHT': 0, 'DOWN': 0, 'LEFT': 0},
 np.int64(13): {'UP': 0, 'RIGHT': 1, 'DOWN': 0, 'LEFT': 0},
 np.int64(14): {'UP': 0, 'RIGHT': 1, 'DOWN': 0, 'LEFT': 0},
 np.int64(15): {'UP': 1, 'RIGHT': 0, 'DOWN': 0, 'LEFT': 0}}

# Voici la politique optimale pour notre agent . Pour chaque state l'agent fait l'action qui maximise la value fonction . Visuellemnt on peut voir que sur chaque state l'agent prend le chemin qui mene vers le l'etat terminal le plus proche

In [10]:
s=policy_iteration(grid_eval)
s

({np.int64(0): 'UP',
  np.int64(1): 'LEFT',
  np.int64(2): 'LEFT',
  np.int64(3): 'LEFT',
  np.int64(4): 'UP',
  np.int64(5): 'LEFT',
  np.int64(6): 'LEFT',
  np.int64(7): 'DOWN',
  np.int64(8): 'UP',
  np.int64(9): 'UP',
  np.int64(10): 'RIGHT',
  np.int64(11): 'DOWN',
  np.int64(12): 'UP',
  np.int64(13): 'RIGHT',
  np.int64(14): 'RIGHT',
  np.int64(15): 'UP'},
 array([  0.        , -13.8687341 , -19.8112877 , -21.79228713,
        -13.8687341 , -17.83891951, -19.82510361, -19.82710344,
        -19.8112877 , -19.82510361, -17.85241947, -13.88981456,
        -21.79228713, -19.82710344, -13.88981456,   0.        ]))

In [8]:
s=value_iteration(grid_eval)
s

array([ 0., -1., -2., -3., -1., -2., -3., -2., -2., -3., -2., -1., -3.,
       -2., -1.,  0.])