In [1]:
import numpy as np
from numba import cuda

In [2]:
@cuda.jit
def doublify(a):
    tx = cuda.threadIdx.x 
    ty = cuda.threadIdx.y
    a[tx, ty] *= 2

In [3]:
a = np.random.randn(4, 4)

In [4]:
a_gpu = cuda.to_device(a)

In [5]:
doublify[1,(4, 4)](a_gpu)

/home/souna/Bureau/Master2/HPC/.venv/lib/python3.12/site-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


In [6]:
a_doubled = a_gpu.copy_to_host()

In [7]:
print(a_doubled)
print(a)
np.allclose(a * 2, a_doubled)

[[-1.32768712  0.23474369  2.92588343  2.89783732]
 [-0.6053389  -0.22535347 -2.41281268 -0.46915861]
 [-1.41565161  0.29835845 -0.20092775  0.57715084]
 [ 2.87964616  2.69909271  1.52180878  1.49906367]]
[[-0.66384356  0.11737184  1.46294172  1.44891866]
 [-0.30266945 -0.11267674 -1.20640634 -0.23457931]
 [-0.70782581  0.14917923 -0.10046387  0.28857542]
 [ 1.43982308  1.34954636  0.76090439  0.74953183]]


True